version: '3'
services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./db_data:/data
    ports:
      - "5432:5432"
    environment:
      PGDATA: /data
      POSTGRES_DB: chat_app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  